### ISSUE TITLE
Default font choice is tough to read

### ISSUE THREAD

**Issue by cbondurant** [EzraSkwarka/COYA_Helper#39]
I find myself getting really stuck trying to read the font.

If I'm being honest I cant fully place what it is but I toyed with the font some while checking and I think the letters are just too vertical, might need just a fully different font choice.

**Comment by EzraSkwarka** [comment]
Gonna do some more research, I'll add a few more Bios fonts and a dyslexic friendly font as options

**Comment by EzraSkwarka** [comment]
See commit above, @cbondurant, give that a try and see if its better please.
