### ISSUE TITLE
Possible rendering error on page 179 of default book

### ISSUE THREAD

**Issue by cbondurant** [EzraSkwarka/COYA_Helper#41]
On page 179 of Citadel of Chaos there is the following: 

> As you step out of the shadows towards the centre of the courtyard, a voice in the wind cries, 'Talt! Stand your ground! You whirl about but can see no-one addressing you. You take another couple of steps. Again, the eerie voice orders you to stop, and this time an arrow zings through the air and lands close to your left foot. You jump back. Still you can see no-one. But now you are stuck.

I suspect it's just something off in the book, but can't be sure.

**Comment by EzraSkwarka** [comment]
See commit above
