### ISSUE TITLE
Pressing tab twice while using OpenDyslexic causes the entire screen to shift, cutting off the `H` in `Home`

### ISSUE THREAD

**Issue by cbondurant** [EzraSkwarka/COYA_Helper#50]
What it says on the tin. 

I have no insight whatsoever as to why this might be.

**Comment by cbondurant** [comment]
forgot to tag. Oops, @EzraSkwarka

**Comment by EzraSkwarka** [comment]
Looks like the issue was with the "#gameText" class as it had both a margin and 'width: 100%' causing everything to overflow left off-screen. Should be fixed on the spacing branch, which I will merge down to dev

**Comment by EzraSkwarka** [comment]
Lost the commit for this, but it should be fixed now
