### ISSUE TITLE
Possible feature: Links on the `ls -books` screen that load a book when clicked.

### ISSUE THREAD

**Issue by cbondurant** [EzraSkwarka/COYA_Helper#51]
Since there is no tab completion for loading a new book (understandably not high priority at the moment to my understanding), and the book paths are rather long, it would improve ergonomics to be able to click and load from the `ls -books` output.

**Comment by cbondurant** [comment]
forgot to tag. Oops, @EzraSkwarka

**Comment by EzraSkwarka** [comment]
Good idea, implemented for the one book that matters in dev branch
